#!/usr/bin/env python3
"""Update UI.xcstrings and Localizable.xcstrings for Phase 5 copy changes."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
UI_PATH = ROOT / "budgetmeter.ios/Resources/UI.xcstrings"
LOCALIZABLE_PATH = ROOT / "budgetmeter.ios/Resources/Localizable.xcstrings"

LOCALES = ["ar", "de", "en", "es", "fr", "it", "ja", "pt", "tr", "zh-Hans"]

UI_UPDATES = {
    "account.title": {
        "en": "Account",
        "tr": "Hesap",
        "de": "Konto",
        "fr": "Compte",
        "es": "Cuenta",
        "it": "Account",
        "pt": "Conta",
        "ja": "アカウント",
        "zh-Hans": "账户",
        "ar": "الحساب",
    },
    "account.footer": {
        "en": "Sign in is free and syncs your data to your account. Manual backup & restore is a Premium feature.",
        "tr": "Giriş ücretsizdir ve verilerinizi hesabınıza eşitler. Manuel yedekleme ve geri yükleme Premium özelliğidir.",
        "de": "Die Anmeldung ist kostenlos und synchronisiert Ihre Daten mit Ihrem Konto. Manuelles Backup & Wiederherstellen ist eine Premium-Funktion.",
        "fr": "La connexion est gratuite et synchronise vos données avec votre compte. La sauvegarde et la restauration manuelles sont une fonctionnalité Premium.",
        "es": "Iniciar sesión es gratis y sincroniza tus datos con tu cuenta. La copia de seguridad y restauración manual es una función Premium.",
        "it": "L'accesso è gratuito e sincronizza i dati con il tuo account. Backup e ripristino manuali sono una funzione Premium.",
        "pt": "O login é gratuito e sincroniza seus dados com sua conta. Backup e restauração manuais são um recurso Premium.",
        "ja": "サインインは無料で、アカウントにデータを同期します。手動バックアップと復元はプレミアム機能です。",
        "zh-Hans": "登录免费，并将数据同步到您的账户。手动备份和恢复是高级功能。",
        "ar": "تسجيل الدخول مجاني ويزامن بياناتك مع حسابك. النسخ الاحتياطي والاستعادة اليدويان ميزة Premium.",
    },
    "account.sign_in_prompt": {
        "en": "Sign in to sync your account data.",
        "tr": "Hesap verilerinizi eşitlemek için giriş yapın.",
        "de": "Melden Sie sich an, um Ihre Kontodaten zu synchronisieren.",
        "fr": "Connectez-vous pour synchroniser les données de votre compte.",
        "es": "Inicia sesión para sincronizar los datos de tu cuenta.",
        "it": "Accedi per sincronizzare i dati del tuo account.",
        "pt": "Entre para sincronizar os dados da sua conta.",
        "ja": "アカウントデータを同期するにはサインインしてください。",
        "zh-Hans": "登录以同步您的账户数据。",
        "ar": "سجّل الدخول لمزامنة بيانات حسابك.",
    },
    "account.delete.message": {
        "en": "This permanently deletes your account and synced data on our servers. Data on this device stays unless you reset it separately in Settings.",
        "tr": "Bu işlem hesabınızı ve sunucularımızdaki eşitlenmiş verileri kalıcı olarak siler. Bu cihazdaki veriler, Ayarlar'dan ayrıca sıfırlamadığınız sürece kalır.",
        "de": "Dies löscht dauerhaft Ihr Konto und synchronisierte Daten auf unseren Servern. Daten auf diesem Gerät bleiben erhalten, sofern Sie sie nicht separat in den Einstellungen zurücksetzen.",
        "fr": "Cela supprime définitivement votre compte et les données synchronisées sur nos serveurs. Les données sur cet appareil restent sauf si vous les réinitialisez séparément dans Réglages.",
        "es": "Esto elimina permanentemente tu cuenta y los datos sincronizados en nuestros servidores. Los datos en este dispositivo permanecen a menos que los restablezcas por separado en Ajustes.",
        "it": "Questo elimina definitivamente il tuo account e i dati sincronizzati sui nostri server. I dati su questo dispositivo restano a meno che non li reimposti separatamente in Impostazioni.",
        "pt": "Isso exclui permanentemente sua conta e os dados sincronizados em nossos servidores. Os dados neste dispositivo permanecem, a menos que você os redefina separadamente em Ajustes.",
        "ja": "アカウントとサーバー上の同期データが永久に削除されます。このデバイスのデータは、設定で別途リセットしない限り残ります。",
        "zh-Hans": "这将永久删除您的账户及我们服务器上的同步数据。除非您在设置中单独重置，否则此设备上的数据会保留。",
        "ar": "يحذف هذا حسابك وبياناتك المتزامنة على خوادمنا بشكل دائم. تبقى البيانات على هذا الجهاز ما لم تُعاد تعيينها بشكل منفصل في الإعدادات.",
    },
    "sync.section.title": {
        "en": "Account Sync",
        "tr": "Hesap Eşitleme",
        "de": "Kontosynchronisierung",
        "fr": "Synchronisation du compte",
        "es": "Sincronización de cuenta",
        "it": "Sincronizzazione account",
        "pt": "Sincronização da conta",
        "ja": "アカウント同期",
        "zh-Hans": "账户同步",
        "ar": "مزامنة الحساب",
    },
    "sync.footer.signed_in": {
        "en": "When you sign in, your BudgetMeter data syncs securely to your account. Sync runs after sign-in and when you make changes. It may take a moment to appear on another device.",
        "tr": "Giriş yaptığınızda BudgetMeter verileriniz hesabınıza güvenle eşitlenir. Eşitleme, girişten sonra ve değişiklik yaptığınızda çalışır. Başka bir cihazda görünmesi biraz zaman alabilir.",
        "de": "Wenn Sie sich anmelden, werden Ihre BudgetMeter-Daten sicher mit Ihrem Konto synchronisiert. Die Synchronisierung erfolgt nach der Anmeldung und bei Änderungen. Es kann einen Moment dauern, bis sie auf einem anderen Gerät erscheinen.",
        "fr": "Lorsque vous vous connectez, vos données BudgetMeter sont synchronisées en toute sécurité avec votre compte. La synchronisation s'exécute après la connexion et lorsque vous apportez des modifications. L'affichage sur un autre appareil peut prendre un moment.",
        "es": "Cuando inicias sesión, tus datos de BudgetMeter se sincronizan de forma segura con tu cuenta. La sincronización se ejecuta después del inicio de sesión y cuando realizas cambios. Puede tardar un momento en aparecer en otro dispositivo.",
        "it": "Quando accedi, i tuoi dati BudgetMeter vengono sincronizzati in modo sicuro con il tuo account. La sincronizzazione avviene dopo l'accesso e quando apporti modifiche. Potrebbe volerci un momento prima che appaia su un altro dispositivo.",
        "pt": "Quando você entra, seus dados do BudgetMeter são sincronizados com segurança com sua conta. A sincronização ocorre após o login e quando você faz alterações. Pode levar um momento para aparecer em outro dispositivo.",
        "ja": "サインインすると、BudgetMeterのデータがアカウントに安全に同期されます。同期はサインイン後および変更時に実行されます。別のデバイスに表示されるまで少し時間がかかる場合があります。",
        "zh-Hans": "登录后，您的 BudgetMeter 数据会安全同步到您的账户。同步在登录后以及您进行更改时运行。在其他设备上显示可能需要一些时间。",
        "ar": "عند تسجيل الدخول، تتم مزامنة بيانات BudgetMeter بأمان مع حسابك. تعمل المزامنة بعد تسجيل الدخول وعند إجراء التغييرات. قد يستغرق ظهورها على جهاز آخر لحظة.",
    },
    "sync.footer.signed_out": {
        "en": "Sign in to save your settings and financial data to your account and use it on another device.",
        "tr": "Ayarlarınızı ve finansal verilerinizi hesabınıza kaydetmek ve başka bir cihazda kullanmak için giriş yapın.",
        "de": "Melden Sie sich an, um Ihre Einstellungen und Finanzdaten in Ihrem Konto zu speichern und auf einem anderen Gerät zu nutzen.",
        "fr": "Connectez-vous pour enregistrer vos réglages et données financières dans votre compte et les utiliser sur un autre appareil.",
        "es": "Inicia sesión para guardar tus ajustes y datos financieros en tu cuenta y usarlos en otro dispositivo.",
        "it": "Accedi per salvare impostazioni e dati finanziari nel tuo account e usarli su un altro dispositivo.",
        "pt": "Entre para salvar suas configurações e dados financeiros na sua conta e usá-los em outro dispositivo.",
        "ja": "設定と財務データをアカウントに保存し、別のデバイスで使用するにはサインインしてください。",
        "zh-Hans": "登录以将设置和财务数据保存到您的账户，并在其他设备上使用。",
        "ar": "سجّل الدخول لحفظ إعداداتك وبياناتك المالية في حسابك واستخدامها على جهاز آخر.",
    },
    "sync.status.active": {
        "en": "Sync enabled for your account",
        "tr": "Hesabınız için eşitleme etkin",
        "de": "Synchronisierung für Ihr Konto aktiviert",
        "fr": "Synchronisation activée pour votre compte",
        "es": "Sincronización activada para tu cuenta",
        "it": "Sincronizzazione attiva per il tuo account",
        "pt": "Sincronização ativada para sua conta",
        "ja": "アカウントの同期が有効です",
        "zh-Hans": "您的账户已启用同步",
        "ar": "المزامنة مفعّلة لحسابك",
    },
    "sync.status.detail": {
        "en": "Updates when you sign in or save changes",
        "tr": "Giriş yaptığınızda veya değişiklik kaydettiğinizde güncellenir",
        "de": "Aktualisiert bei Anmeldung oder beim Speichern von Änderungen",
        "fr": "Mise à jour lors de la connexion ou de l'enregistrement des modifications",
        "es": "Se actualiza al iniciar sesión o guardar cambios",
        "it": "Si aggiorna quando accedi o salvi modifiche",
        "pt": "Atualiza quando você entra ou salva alterações",
        "ja": "サインインまたは変更保存時に更新されます",
        "zh-Hans": "在您登录或保存更改时更新",
        "ar": "يتم التحديث عند تسجيل الدخول أو حفظ التغييرات",
    },
    "backup.section.title": {
        "en": "Manual Backup & Restore",
        "tr": "Manuel Yedekleme ve Geri Yükleme",
        "de": "Manuelles Backup & Wiederherstellen",
        "fr": "Sauvegarde et restauration manuelles",
        "es": "Copia de seguridad y restauración manual",
        "it": "Backup e ripristino manuali",
        "pt": "Backup e restauração manuais",
        "ja": "手動バックアップと復元",
        "zh-Hans": "手动备份和恢复",
        "ar": "النسخ الاحتياطي والاستعادة اليدويان",
    },
    "backup.footer": {
        "en": "Optional full-device snapshot for advanced recovery. This is separate from everyday account sync. Local data is snapshotted before backup or restore.",
        "tr": "Gelişmiş kurtarma için isteğe bağlı tam cihaz anlık görüntüsü. Günlük hesap eşitlemesinden ayrıdır. Yedekleme veya geri yüklemeden önce yerel verilerin anlık görüntüsü alınır.",
        "de": "Optionale vollständige Gerätesicherung für erweiterte Wiederherstellung. Getrennt von der täglichen Kontosynchronisierung. Lokale Daten werden vor Backup oder Wiederherstellung gesichert.",
        "fr": "Instantané complet optionnel de l'appareil pour une récupération avancée. Séparé de la synchronisation quotidienne du compte. Les données locales sont sauvegardées avant sauvegarde ou restauration.",
        "es": "Instantánea opcional del dispositivo completo para recuperación avanzada. Separada de la sincronización diaria de la cuenta. Los datos locales se guardan antes de la copia o restauración.",
        "it": "Istantanea completa opzionale del dispositivo per recupero avanzato. Separata dalla sincronizzazione quotidiana dell'account. I dati locali vengono salvati prima del backup o ripristino.",
        "pt": "Instantâneo completo opcional do dispositivo para recuperação avançada. Separado da sincronização diária da conta. Os dados locais são salvos antes do backup ou restauração.",
        "ja": "高度な復旧のための任意の全デバイススナップショット。日常のアカウント同期とは別です。バックアップまたは復元の前にローカルデータのスナップショットを取得します。",
        "zh-Hans": "用于高级恢复的可选全设备快照。与日常账户同步分开。在备份或恢复前会对本地数据创建快照。",
        "ar": "لقطة اختيارية كاملة للجهاز للاستعادة المتقدمة. منفصلة عن مزامنة الحساب اليومية. يتم أخذ لقطة للبيانات المحلية قبل النسخ الاحتياطي أو الاستعادة.",
    },
    "backup.premium_required": {
        "en": "Upgrade for Manual Backup & Restore",
        "tr": "Manuel Yedekleme ve Geri Yükleme için Yükselt",
        "de": "Upgrade für manuelles Backup & Wiederherstellen",
        "fr": "Passer à Premium pour la sauvegarde et restauration manuelles",
        "es": "Mejorar para copia de seguridad y restauración manual",
        "it": "Passa a Premium per backup e ripristino manuali",
        "pt": "Atualizar para backup e restauração manuais",
        "ja": "手動バックアップと復元にアップグレード",
        "zh-Hans": "升级以使用手动备份和恢复",
        "ar": "ترقية للنسخ الاحتياطي والاستعادة اليدويين",
    },
    "backup.sign_in_required": {
        "en": "Sign in to use manual backup & restore.",
        "tr": "Manuel yedekleme ve geri yükleme için giriş yapın.",
        "de": "Melden Sie sich an, um manuelles Backup & Wiederherstellen zu nutzen.",
        "fr": "Connectez-vous pour utiliser la sauvegarde et la restauration manuelles.",
        "es": "Inicia sesión para usar la copia de seguridad y restauración manual.",
        "it": "Accedi per usare backup e ripristino manuali.",
        "pt": "Entre para usar backup e restauração manuais.",
        "ja": "手動バックアップと復元を使用するにはサインインしてください。",
        "zh-Hans": "登录以使用手动备份和恢复。",
        "ar": "سجّل الدخول لاستخدام النسخ الاحتياطي والاستعادة اليدويين.",
    },
    "backup.never": {
        "en": "No manual backup yet",
        "tr": "Henüz manuel yedek yok",
        "de": "Noch kein manuelles Backup",
        "fr": "Pas encore de sauvegarde manuelle",
        "es": "Aún no hay copia de seguridad manual",
        "it": "Nessun backup manuale ancora",
        "pt": "Nenhum backup manual ainda",
        "ja": "手動バックアップはまだありません",
        "zh-Hans": "尚无手动备份",
        "ar": "لا يوجد نسخ احتياطي يدوي بعد",
    },
    "backup.cloud_summary": {
        "en": "Manual backup: %lld records, %@",
        "tr": "Manuel yedek: %lld kayıt, %@",
        "de": "Manuelles Backup: %lld Datensätze, %@",
        "fr": "Sauvegarde manuelle : %lld enregistrements, %@",
        "es": "Copia manual: %lld registros, %@",
        "it": "Backup manuale: %lld record, %@",
        "pt": "Backup manual: %lld registros, %@",
        "ja": "手動バックアップ: %lld 件、%@",
        "zh-Hans": "手动备份：%lld 条记录，%@",
        "ar": "نسخ احتياطي يدوي: %lld سجل، %@",
    },
    "backup.restore": {
        "en": "Restore Manual Backup",
        "tr": "Manuel Yedeği Geri Yükle",
        "de": "Manuelles Backup wiederherstellen",
        "fr": "Restaurer la sauvegarde manuelle",
        "es": "Restaurar copia manual",
        "it": "Ripristina backup manuale",
        "pt": "Restaurar backup manual",
        "ja": "手動バックアップを復元",
        "zh-Hans": "恢复手动备份",
        "ar": "استعادة النسخ الاحتياطي اليدوي",
    },
    "backup.restore.confirm.title": {
        "en": "Restore Manual Backup",
        "tr": "Manuel Yedeği Geri Yükle",
        "de": "Manuelles Backup wiederherstellen",
        "fr": "Restaurer la sauvegarde manuelle",
        "es": "Restaurar copia manual",
        "it": "Ripristina backup manuale",
        "pt": "Restaurar backup manual",
        "ja": "手動バックアップを復元",
        "zh-Hans": "恢复手动备份",
        "ar": "استعادة النسخ الاحتياطي اليدوي",
    },
    "backup.restore.confirm.message": {
        "en": "This replaces local data on this device with your manual backup.",
        "tr": "Bu işlem bu cihazdaki yerel verileri manuel yedeğinizle değiştirir.",
        "de": "Dies ersetzt lokale Daten auf diesem Gerät durch Ihr manuelles Backup.",
        "fr": "Cela remplace les données locales sur cet appareil par votre sauvegarde manuelle.",
        "es": "Esto reemplaza los datos locales en este dispositivo con tu copia de seguridad manual.",
        "it": "Questo sostituisce i dati locali su questo dispositivo con il backup manuale.",
        "pt": "Isso substitui os dados locais neste dispositivo pelo backup manual.",
        "ja": "このデバイスのローカルデータが手動バックアップで置き換えられます。",
        "zh-Hans": "这将用您的手动备份替换此设备上的本地数据。",
        "ar": "يستبدل هذا البيانات المحلية على هذا الجهاز بالنسخ الاحتياطي اليدوي.",
    },
    "backup.overlap.message": {
        "en": "This device and your manual backup both contain data. Choose backup or restore carefully.",
        "tr": "Bu cihaz ve manuel yedeğinizin ikisinde de veri var. Yedekleme veya geri yüklemeyi dikkatli seçin.",
        "de": "Dieses Gerät und Ihr manuelles Backup enthalten beide Daten. Wählen Sie Backup oder Wiederherstellung sorgfältig.",
        "fr": "Cet appareil et votre sauvegarde manuelle contiennent tous deux des données. Choisissez soigneusement sauvegarde ou restauration.",
        "es": "Este dispositivo y tu copia manual contienen datos. Elige copia o restauración con cuidado.",
        "it": "Questo dispositivo e il backup manuale contengono entrambi dati. Scegli backup o ripristino con attenzione.",
        "pt": "Este dispositivo e seu backup manual contêm dados. Escolha backup ou restauração com cuidado.",
        "ja": "このデバイスと手動バックアップの両方にデータがあります。バックアップまたは復元を慎重に選んでください。",
        "zh-Hans": "此设备和您的手动备份都包含数据。请谨慎选择备份或恢复。",
        "ar": "يحتوي هذا الجهاز والنسخ الاحتياطي اليدوي على بيانات. اختر النسخ الاحتياطي أو الاستعادة بعناية.",
    },
    "backup.error.not_configured": {
        "en": "Manual backup is not configured.",
        "tr": "Manuel yedekleme yapılandırılmamış.",
        "de": "Manuelles Backup ist nicht konfiguriert.",
        "fr": "La sauvegarde manuelle n'est pas configurée.",
        "es": "La copia de seguridad manual no está configurada.",
        "it": "Il backup manuale non è configurato.",
        "pt": "O backup manual não está configurado.",
        "ja": "手動バックアップが設定されていません。",
        "zh-Hans": "手动备份未配置。",
        "ar": "النسخ الاحتياطي اليدوي غير مهيأ.",
    },
    "backup.error.not_authenticated": {
        "en": "Sign in to use manual backup & restore.",
        "tr": "Manuel yedekleme ve geri yükleme için giriş yapın.",
        "de": "Melden Sie sich an, um manuelles Backup & Wiederherstellen zu nutzen.",
        "fr": "Connectez-vous pour utiliser la sauvegarde et la restauration manuelles.",
        "es": "Inicia sesión para usar la copia de seguridad y restauración manual.",
        "it": "Accedi per usare backup e ripristino manuali.",
        "pt": "Entre para usar backup e restauração manuais.",
        "ja": "手動バックアップと復元を使用するにはサインインしてください。",
        "zh-Hans": "登录以使用手动备份和恢复。",
        "ar": "سجّل الدخول لاستخدام النسخ الاحتياطي والاستعادة اليدويين.",
    },
    "backup.error.premium_required": {
        "en": "Manual backup & restore requires BudgetMeter Premium.",
        "tr": "Manuel yedekleme ve geri yükleme BudgetMeter Premium gerektirir.",
        "de": "Manuelles Backup & Wiederherstellen erfordert BudgetMeter Premium.",
        "fr": "La sauvegarde et la restauration manuelles nécessitent BudgetMeter Premium.",
        "es": "La copia de seguridad y restauración manual requieren BudgetMeter Premium.",
        "it": "Backup e ripristino manuali richiedono BudgetMeter Premium.",
        "pt": "Backup e restauração manuais exigem BudgetMeter Premium.",
        "ja": "手動バックアップと復元にはBudgetMeter Premiumが必要です。",
        "zh-Hans": "手动备份和恢复需要 BudgetMeter Premium。",
        "ar": "يتطلب النسخ الاحتياطي والاستعادة اليدويان BudgetMeter Premium.",
    },
    "backup.error.offline": {
        "en": "Manual backup is unavailable offline.",
        "tr": "Manuel yedekleme çevrimdışı kullanılamaz.",
        "de": "Manuelles Backup ist offline nicht verfügbar.",
        "fr": "La sauvegarde manuelle n'est pas disponible hors ligne.",
        "es": "La copia de seguridad manual no está disponible sin conexión.",
        "it": "Il backup manuale non è disponibile offline.",
        "pt": "O backup manual não está disponível offline.",
        "ja": "手動バックアップはオフラインでは利用できません。",
        "zh-Hans": "离线时无法使用手动备份。",
        "ar": "النسخ الاحتياطي اليدوي غير متاح دون اتصال.",
    },
    "backup.error.no_cloud_backup": {
        "en": "No manual backup found for this account.",
        "tr": "Bu hesap için manuel yedek bulunamadı.",
        "de": "Kein manuelles Backup für dieses Konto gefunden.",
        "fr": "Aucune sauvegarde manuelle trouvée pour ce compte.",
        "es": "No se encontró copia de seguridad manual para esta cuenta.",
        "it": "Nessun backup manuale trovato per questo account.",
        "pt": "Nenhum backup manual encontrado para esta conta.",
        "ja": "このアカウントの手動バックアップが見つかりません。",
        "zh-Hans": "未找到此账户的手动备份。",
        "ar": "لم يتم العثور على نسخ احتياطي يدوي لهذا الحساب.",
    },
    "settings.account.title": {
        "en": "Account",
        "tr": "Hesap",
        "de": "Konto",
        "fr": "Compte",
        "es": "Cuenta",
        "it": "Account",
        "pt": "Conta",
        "ja": "アカウント",
        "zh-Hans": "账户",
        "ar": "الحساب",
    },
    "settings.account.subtitle": {
        "en": "Sign in to sync your data",
        "tr": "Verilerinizi eşitlemek için giriş yapın",
        "de": "Anmelden, um Ihre Daten zu synchronisieren",
        "fr": "Connectez-vous pour synchroniser vos données",
        "es": "Inicia sesión para sincronizar tus datos",
        "it": "Accedi per sincronizzare i tuoi dati",
        "pt": "Entre para sincronizar seus dados",
        "ja": "データを同期するにはサインイン",
        "zh-Hans": "登录以同步您的数据",
        "ar": "سجّل الدخول لمزامنة بياناتك",
    },
    "settings.privacy.policy.data_collect.content": {
        "en": "• Financial data (income, expenses, categories) — stored locally on your device\n• App preferences (currency, language) — stored locally\n• Account sync data (when signed in) — settings, goals, bills, transactions, and categories stored in your Supabase account\n• Optional Premium manual backup snapshots — separate from everyday sync",
        "tr": "• Finansal veriler (gelir, gider, kategoriler) — cihazınızda yerel olarak saklanır\n• Uygulama tercihleri (para birimi, dil) — yerel olarak saklanır\n• Hesap eşitleme verileri (giriş yapıldığında) — ayarlar, hedefler, faturalar, işlemler ve kategoriler Supabase hesabınızda saklanır\n• İsteğe bağlı Premium manuel yedek anlık görüntüleri — günlük eşitlemeden ayrı",
        "de": "• Finanzdaten (Einkommen, Ausgaben, Kategorien) — lokal auf Ihrem Gerät gespeichert\n• App-Einstellungen (Währung, Sprache) — lokal gespeichert\n• Kontosynchronisierungsdaten (bei Anmeldung) — Einstellungen, Ziele, Rechnungen, Transaktionen und Kategorien in Ihrem Supabase-Konto\n• Optionale Premium-Manualsicherungen — getrennt von der täglichen Synchronisierung",
        "fr": "• Données financières (revenus, dépenses, catégories) — stockées localement sur votre appareil\n• Préférences de l'app (devise, langue) — stockées localement\n• Données de synchronisation du compte (connecté) — réglages, objectifs, factures, transactions et catégories dans votre compte Supabase\n• Instantanés de sauvegarde manuelle Premium optionnels — séparés de la synchronisation quotidienne",
        "es": "• Datos financieros (ingresos, gastos, categorías) — almacenados localmente en tu dispositivo\n• Preferencias de la app (moneda, idioma) — almacenadas localmente\n• Datos de sincronización de cuenta (con sesión iniciada) — ajustes, metas, facturas, transacciones y categorías en tu cuenta Supabase\n• Instantáneas de copia manual Premium opcionales — separadas de la sincronización diaria",
        "it": "• Dati finanziari (entrate, spese, categorie) — memorizzati localmente sul dispositivo\n• Preferenze app (valuta, lingua) — memorizzate localmente\n• Dati sincronizzazione account (con accesso) — impostazioni, obiettivi, bollette, transazioni e categorie nel tuo account Supabase\n• Snapshot backup manuali Premium opzionali — separati dalla sincronizzazione quotidiana",
        "pt": "• Dados financeiros (receitas, despesas, categorias) — armazenados localmente no dispositivo\n• Preferências do app (moeda, idioma) — armazenadas localmente\n• Dados de sincronização da conta (conectado) — configurações, metas, contas, transações e categorias na sua conta Supabase\n• Instantâneos de backup manual Premium opcionais — separados da sincronização diária",
        "ja": "• 財務データ（収入、支出、カテゴリ）— デバイスにローカル保存\n• アプリ設定（通貨、言語）— ローカル保存\n• アカウント同期データ（サインイン時）— 設定、目標、請求、取引、カテゴリをSupabaseアカウントに保存\n• 任意のプレミアム手動バックアップスナップショット — 日常の同期とは別",
        "zh-Hans": "• 财务数据（收入、支出、类别）— 本地存储在您的设备上\n• 应用偏好（货币、语言）— 本地存储\n• 账户同步数据（登录时）— 设置、目标、账单、交易和类别存储在您的 Supabase 账户\n• 可选的高级手动备份快照 — 与日常同步分开",
        "ar": "• البيانات المالية (الدخل، المصروفات، الفئات) — مخزنة محلياً على جهازك\n• تفضيلات التطبيق (العملة، اللغة) — مخزنة محلياً\n• بيانات مزامنة الحساب (عند تسجيل الدخول) — الإعدادات والأهداف والفواتير والمعاملات والفئات في حساب Supabase\n• لقطات نسخ احتياطي يدوي Premium اختيارية — منفصلة عن المزامنة اليومية",
    },
    "settings.privacy.policy.data_use.content": {
        "en": "• To provide financial tracking functionality\n• To sync your account data when you sign in\n• To back up and restore optional Premium manual snapshots when you choose",
        "tr": "• Finansal takip işlevselliği sağlamak için\n• Giriş yaptığınızda hesap verilerinizi eşitlemek için\n• Seçtiğinizde isteğe bağlı Premium manuel anlık görüntüleri yedeklemek ve geri yüklemek için",
        "de": "• Zur Bereitstellung der Finanzverfolgungsfunktion\n• Zur Synchronisierung Ihrer Kontodaten bei Anmeldung\n• Zum Sichern und Wiederherstellen optionaler Premium-Manualsicherungen auf Wunsch",
        "fr": "• Pour fournir la fonctionnalité de suivi financier\n• Pour synchroniser vos données de compte lors de la connexion\n• Pour sauvegarder et restaurer des instantanés manuels Premium optionnels si vous le choisissez",
        "es": "• Para proporcionar la funcionalidad de seguimiento financiero\n• Para sincronizar los datos de tu cuenta al iniciar sesión\n• Para respaldar y restaurar instantáneas manuales Premium opcionales cuando elijas",
        "it": "• Per fornire la funzionalità di tracciamento finanziario\n• Per sincronizzare i dati dell'account quando accedi\n• Per eseguire backup e ripristino di snapshot manuali Premium opzionali quando scegli",
        "pt": "• Para fornecer a funcionalidade de rastreamento financeiro\n• Para sincronizar os dados da sua conta ao entrar\n• Para fazer backup e restaurar instantâneos manuais Premium opcionais quando você escolher",
        "ja": "• 財務追跡機能を提供するため\n• サインイン時にアカウントデータを同期するため\n• 選択時に任意のプレミアム手動スナップショットをバックアップ・復元するため",
        "zh-Hans": "• 提供财务跟踪功能\n• 在您登录时同步账户数据\n• 在您选择时备份和恢复可选的高级手动快照",
        "ar": "• لتوفير وظيفة التتبع المالي\n• لمزامنة بيانات حسابك عند تسجيل الدخول\n• لنسخ واستعادة لقطات يدوية Premium اختيارية عند اختيارك",
    },
    "settings.privacy.policy.data_sharing.content": {
        "en": "We do not sell your personal data. Account sync and optional manual backup use Supabase over HTTPS. We do not share your data with advertisers or other third parties.",
        "tr": "Kişisel verilerinizi satmıyoruz. Hesap eşitleme ve isteğe bağlı manuel yedekleme HTTPS üzerinden Supabase kullanır. Verilerinizi reklamverenler veya üçüncü taraflarla paylaşmıyoruz.",
        "de": "Wir verkaufen Ihre personenbezogenen Daten nicht. Kontosynchronisierung und optionales manuelles Backup nutzen Supabase über HTTPS. Wir teilen Ihre Daten nicht mit Werbetreibenden oder Dritten.",
        "fr": "Nous ne vendons pas vos données personnelles. La synchronisation du compte et la sauvegarde manuelle optionnelle utilisent Supabase via HTTPS. Nous ne partageons pas vos données avec des annonceurs ou des tiers.",
        "es": "No vendemos tus datos personales. La sincronización de cuenta y la copia manual opcional usan Supabase por HTTPS. No compartimos tus datos con anunciantes ni terceros.",
        "it": "Non vendiamo i tuoi dati personali. La sincronizzazione dell'account e il backup manuale opzionale usano Supabase via HTTPS. Non condividiamo i tuoi dati con inserzionisti o terze parti.",
        "pt": "Não vendemos seus dados pessoais. A sincronização da conta e o backup manual opcional usam Supabase via HTTPS. Não compartilhamos seus dados com anunciantes ou terceiros.",
        "ja": "個人データを販売することはありません。アカウント同期と任意の手動バックアップはHTTPS経由でSupabaseを使用します。広告主や第三者とデータを共有することはありません。",
        "zh-Hans": "我们不出售您的个人数据。账户同步和可选的手动备份通过 HTTPS 使用 Supabase。我们不会与广告商或其他第三方共享您的数据。",
        "ar": "لا نبيع بياناتك الشخصية. تستخدم مزامنة الحساب والنسخ الاحتياطي اليدوي الاختياري Supabase عبر HTTPS. لا نشارك بياناتك مع المعلنين أو أطراف ثالثة.",
    },
    "settings.privacy.policy.data_storage.content": {
        "en": "• Local: Core Data database on your device\n• Account sync: Supabase (when signed in)\n• Manual backup (Premium, optional): full snapshot in user_backups",
        "tr": "• Yerel: Cihazınızdaki Core Data veritabanı\n• Hesap eşitleme: Supabase (giriş yapıldığında)\n• Manuel yedekleme (Premium, isteğe bağlı): user_backups içinde tam anlık görüntü",
        "de": "• Lokal: Core-Data-Datenbank auf Ihrem Gerät\n• Kontosynchronisierung: Supabase (bei Anmeldung)\n• Manuelles Backup (Premium, optional): vollständige Sicherung in user_backups",
        "fr": "• Local : base de données Core Data sur votre appareil\n• Synchronisation du compte : Supabase (connecté)\n• Sauvegarde manuelle (Premium, optionnelle) : instantané complet dans user_backups",
        "es": "• Local: base de datos Core Data en tu dispositivo\n• Sincronización de cuenta: Supabase (con sesión iniciada)\n• Copia manual (Premium, opcional): instantánea completa en user_backups",
        "it": "• Locale: database Core Data sul dispositivo\n• Sincronizzazione account: Supabase (con accesso)\n• Backup manuale (Premium, opzionale): snapshot completo in user_backups",
        "pt": "• Local: banco de dados Core Data no dispositivo\n• Sincronização da conta: Supabase (conectado)\n• Backup manual (Premium, opcional): instantâneo completo em user_backups",
        "ja": "• ローカル: デバイスのCore Dataデータベース\n• アカウント同期: Supabase（サインイン時）\n• 手動バックアップ（プレミアム、任意）: user_backups内の完全スナップショット",
        "zh-Hans": "• 本地：设备上的 Core Data 数据库\n• 账户同步：Supabase（登录时）\n• 手动备份（高级，可选）：user_backups 中的完整快照",
        "ar": "• محلي: قاعدة بيانات Core Data على جهازك\n• مزامنة الحساب: Supabase (عند تسجيل الدخول)\n• نسخ احتياطي يدوي (Premium، اختياري): لقطة كاملة في user_backups",
    },
    "settings.privacy.policy.your_rights.content": {
        "en": "• Access: View all your data within the app\n• Delete local data: Reset all data via Settings\n• Delete account: Delete account in Account — removes synced server data\n• Control: Sign out anytime; manual backup is optional and Premium",
        "tr": "• Erişim: Tüm verilerinizi uygulama içinde görüntüleyin\n• Yerel verileri sil: Ayarlar'dan tüm verileri sıfırlayın\n• Hesabı sil: Hesap bölümünden hesabı silin — eşitlenmiş sunucu verilerini kaldırır\n• Kontrol: İstediğiniz zaman çıkış yapın; manuel yedekleme isteğe bağlı ve Premium'dur",
        "de": "• Zugriff: Alle Daten in der App anzeigen\n• Lokale Daten löschen: Alle Daten in Einstellungen zurücksetzen\n• Konto löschen: Konto unter Konto löschen — entfernt synchronisierte Serverdaten\n• Kontrolle: Jederzeit abmelden; manuelles Backup ist optional und Premium",
        "fr": "• Accès : voir toutes vos données dans l'app\n• Supprimer les données locales : réinitialiser via Réglages\n• Supprimer le compte : supprimer le compte dans Compte — supprime les données serveur synchronisées\n• Contrôle : déconnexion à tout moment ; sauvegarde manuelle optionnelle et Premium",
        "es": "• Acceso: ver todos tus datos en la app\n• Eliminar datos locales: restablecer todo en Ajustes\n• Eliminar cuenta: eliminar cuenta en Cuenta — elimina datos sincronizados del servidor\n• Control: cerrar sesión en cualquier momento; copia manual opcional y Premium",
        "it": "• Accesso: visualizza tutti i dati nell'app\n• Elimina dati locali: reimposta tutto in Impostazioni\n• Elimina account: elimina account in Account — rimuove i dati sincronizzati sul server\n• Controllo: esci in qualsiasi momento; backup manuale opzionale e Premium",
        "pt": "• Acesso: ver todos os dados no app\n• Excluir dados locais: redefinir tudo em Ajustes\n• Excluir conta: excluir conta em Conta — remove dados sincronizados do servidor\n• Controle: sair a qualquer momento; backup manual opcional e Premium",
        "ja": "• アクセス: アプリ内ですべてのデータを表示\n• ローカルデータ削除: 設定ですべてのデータをリセット\n• アカウント削除: アカウントでアカウントを削除 — 同期されたサーバーデータを削除\n• 管理: いつでもサインアウト; 手動バックアップは任意でプレミアム",
        "zh-Hans": "• 访问：在应用内查看所有数据\n• 删除本地数据：在设置中重置所有数据\n• 删除账户：在账户中删除账户 — 移除同步的服务器数据\n• 控制：随时退出登录；手动备份为可选高级功能",
        "ar": "• الوصول: عرض جميع بياناتك داخل التطبيق\n• حذف البيانات المحلية: إعادة تعيين جميع البيانات عبر الإعدادات\n• حذف الحساب: حذف الحساب في الحساب — يزيل بيانات الخادم المتزامنة\n• التحكم: تسجيل الخروج في أي وقت؛ النسخ الاحتياطي اليدوي اختياري وPremium",
    },
}

LOCALIZABLE_UPDATES = {
    "settings.privacy.sheet.intro": {
        "en": "Your data is stored locally on your device. When you sign in, your account data syncs to Supabase. Premium users can optionally create manual backup snapshots.",
        "tr": "Verileriniz cihazınızda yerel olarak saklanır. Giriş yaptığınızda hesap verileriniz Supabase'e eşitlenir. Premium kullanıcılar isteğe bağlı olarak manuel yedek anlık görüntüleri oluşturabilir.",
        "de": "Ihre Daten werden lokal auf Ihrem Gerät gespeichert. Bei Anmeldung werden Ihre Kontodaten mit Supabase synchronisiert. Premium-Nutzer können optional manuelle Backups erstellen.",
        "fr": "Vos données sont stockées localement sur votre appareil. Lorsque vous vous connectez, vos données de compte sont synchronisées avec Supabase. Les utilisateurs Premium peuvent créer des sauvegardes manuelles optionnelles.",
        "es": "Tus datos se almacenan localmente en tu dispositivo. Cuando inicias sesión, tus datos de cuenta se sincronizan con Supabase. Los usuarios Premium pueden crear instantáneas de copia manual opcionales.",
        "it": "I tuoi dati sono memorizzati localmente sul dispositivo. Quando accedi, i dati dell'account vengono sincronizzati con Supabase. Gli utenti Premium possono creare snapshot di backup manuali opzionali.",
        "pt": "Seus dados são armazenados localmente no dispositivo. Quando você entra, os dados da conta são sincronizados com o Supabase. Usuários Premium podem criar instantâneos de backup manual opcionais.",
        "ja": "データはデバイスにローカル保存されます。サインインすると、アカウントデータがSupabaseに同期されます。プレミアムユーザーは任意で手動バックアップスナップショットを作成できます。",
        "zh-Hans": "您的数据本地存储在设备上。登录后，账户数据会同步到 Supabase。高级用户可以选择创建手动备份快照。",
        "ar": "يتم تخزين بياناتك محلياً على جهازك. عند تسجيل الدخول، تتم مزامنة بيانات حسابك مع Supabase. يمكن للمستخدمين Premium إنشاء لقطات نسخ احتياطي يدوي اختيارية.",
    },
    "settings.privacy.sheet.bullet.icloud": {
        "en": "Premium users can optionally save manual backup snapshots to Supabase. This is separate from everyday account sync.",
        "tr": "Premium kullanıcılar isteğe bağlı olarak manuel yedek anlık görüntülerini Supabase'e kaydedebilir. Bu, günlük hesap eşitlemesinden ayrıdır.",
        "de": "Premium-Nutzer können optional manuelle Backups in Supabase speichern. Dies ist getrennt von der täglichen Kontosynchronisierung.",
        "fr": "Les utilisateurs Premium peuvent enregistrer des sauvegardes manuelles optionnelles sur Supabase. C'est séparé de la synchronisation quotidienne du compte.",
        "es": "Los usuarios Premium pueden guardar instantáneas de copia manual opcionales en Supabase. Esto es independiente de la sincronización diaria de la cuenta.",
        "it": "Gli utenti Premium possono salvare snapshot di backup manuali opzionali su Supabase. Questo è separato dalla sincronizzazione quotidiana dell'account.",
        "pt": "Usuários Premium podem salvar instantâneos de backup manual opcionais no Supabase. Isso é separado da sincronização diária da conta.",
        "ja": "プレミアムユーザーは任意で手動バックアップスナップショットをSupabaseに保存できます。これは日常のアカウント同期とは別です。",
        "zh-Hans": "高级用户可以选择将手动备份快照保存到 Supabase。这与日常账户同步分开。",
        "ar": "يمكن للمستخدمين Premium حفظ لقطات نسخ احتياطي يدوي اختيارية في Supabase. هذا منفصل عن مزامنة الحساب اليومية.",
    },
}


def make_entry(translations: dict) -> dict:
    localizations = {}
    for locale in LOCALES:
        value = translations.get(locale, translations["en"])
        localizations[locale] = {
            "stringUnit": {"state": "translated", "value": value}
        }
    return {"extractionState": "manual", "localizations": localizations}


def apply_updates(path: Path, updates: dict) -> None:
    with path.open(encoding="utf-8") as f:
        catalog = json.load(f)
    strings = catalog.setdefault("strings", {})
    for key, translations in updates.items():
        strings[key] = make_entry(translations)
    with path.open("w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Updated {len(updates)} keys in {path.name}")


def main() -> None:
    apply_updates(UI_PATH, UI_UPDATES)
    apply_updates(LOCALIZABLE_PATH, LOCALIZABLE_UPDATES)


if __name__ == "__main__":
    main()
